---
# handlers file for openvpn_as

- name: update db
  become: yes
  command: "./confdba --load --file={{ openvpn_as_etc_directory }}/config.json"
  args:
    chdir: "{{ openvpn_as_scripts_directory }}"
  tags:
    - openvpn_as

- name: restart openvpn_as
  become: yes
  service:
    name: "{{ openvpn_as_service_name }}"
    state: restarted
  tags:
    - openvpn_as
